M48
; DRILL file {KiCad 8.0.3+1} date 2024-07-15T22:27:20+0000
; FORMAT={3:3/ absolute / metric / suppress leading zeros}
; #@! TF.CreationDate,2024-07-15T22:27:20+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3+1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC,TZ
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.900
%
G90
G05
T1
X99600Y-72700
X99600Y-83700
T2
X109600Y-75700
X109600Y-80700
M30
